/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PodscriberRouteImport } from './routes/podscriber'
import { Route as LoggerRouteImport } from './routes/logger'
import { Route as IndexRouteImport } from './routes/index'

const PodscriberRoute = PodscriberRouteImport.update({
  id: '/podscriber',
  path: '/podscriber',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggerRoute = LoggerRouteImport.update({
  id: '/logger',
  path: '/logger',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logger': typeof LoggerRoute
  '/podscriber': typeof PodscriberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logger': typeof LoggerRoute
  '/podscriber': typeof PodscriberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logger': typeof LoggerRoute
  '/podscriber': typeof PodscriberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logger' | '/podscriber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logger' | '/podscriber'
  id: '__root__' | '/' | '/logger' | '/podscriber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoggerRoute: typeof LoggerRoute
  PodscriberRoute: typeof PodscriberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/podscriber': {
      id: '/podscriber'
      path: '/podscriber'
      fullPath: '/podscriber'
      preLoaderRoute: typeof PodscriberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logger': {
      id: '/logger'
      path: '/logger'
      fullPath: '/logger'
      preLoaderRoute: typeof LoggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoggerRoute: LoggerRoute,
  PodscriberRoute: PodscriberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
