name: Dependabot Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    # Only run if the PR is from Dependabot
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-and-build
