name: Go Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule: # everyday at 2301 UTC or 0001 CET (next day)
    - cron: '1 23 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Build
      run: go build ./...

    - name: Run
      run: ./debugjois.dev build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Upload to S3
      run: ./debugjois.dev upload
