name: latest-deps

on:
  push:
  pull_request:
  schedule:
    - cron: '22 10 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go get -u -t ./...
      - run: go test ./...
