name: latest-deps

on:
  push:
  pull_request:
  schedule:
    - cron: '22 10 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-and-build
        with:
          build: 'false'
      - run: go get -u -t ./...
      - run: go test ./...
