name: Site Newsletter

on:
  workflow_dispatch:
  schedule: # every Sunday at 3am CET (2am UTC)
    - cron: '0 2 * * 0'

jobs:
  post-newsletter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: site

    steps:
    - uses: actions/checkout@v6

    - uses: ./.github/actions/site-setup-and-build

    - name: Post to Buttondown
      env:
        BUTTONDOWN_API_KEY: ${{ secrets.BUTTONDOWN_API_KEY }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      run: ./debugjois.dev build-newsletter --post --notify
