name: Vulnerability Check

on:
  pull_request:
  schedule:
    - cron: '22 10 * * *'

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.work'
          cache: true
          cache-dependency-path: |
            site/go.sum
            backend/api/go.sum
            infra/go.sum
      - name: Run govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
